### ISSUE TITLE
Some issues and feeback

### ISSUE THREAD

**Issue by gerardroche** [francescarpi/RelativeLineNumbers#1]
If you clone the package into the Packages directory (manual installation) then the `package-metadata.json` in the root of the package causes the package to be auto uninstalled by Package Control. I don't know why this happens, PC must use a metadata file like that. You don't need that file so you can remove it which solves the issue.

I've hacked around trying to see if it was possible to fix some issues, a wip is here: https://github.com/gerardroche/RelativeLineNumbers/tree/wip. You might find it useful.

Disclainer: I'm not convinced Phantoms or any solution other than an one in the core will work for relative line number feature. I encountered too many problems. Performance for a feature like this is paramount. 

Some issues I encountered:

* The width changes too much when scrolling: You can solve this by setting the width using the last line number and padding the visible line numbers to that size.
* An option to set the current line number instead of zero.
* Scrolling with the mouse wheel shows no relative line number column and causes the editor area to then shift to the right when the phantoms are updated. This is a blocker issue.
* When lines are too long the horizontal scoll bar moves to the right hiding the relative line number column. Clicking around with the mouse also cause the it to scroll to the right hiding the rln col too. This is also blocker issue.
* The auto complete popup flashes (blinks) really fast when open. I couldn't figure out why that happens. Looks like the when the phantoms are being redrawn it affecting the popup.

**Comment by francescarpi** [comment]
Hi! 

I know that this package have some bugs and is not stable. I will be very grateful if you can help me to improve and send me a pull request. :)

Best regards

**Comment by francescarpi** [comment]
Hi.

I've added a new option for set current line char. 
And I have split your issues in separate tickets.

Please, consider if is necessary close this ticket.

**Comment by gerardroche** [comment]
This is good to close.

After more testing I don't think it's possible to implement relative line numbers with phantoms. At least not a good enough one for it to be usable. There are too many issues and core api limitations.

**Comment by francescarpi** [comment]
Hi,
Yes. You're right. I think so, too. :(

**Comment by gerardroche** [comment]
Reminds me of the Block cursor issues (https://github.com/NeoVintageous/NeoVintageous/issues/261#issuecomment-306333759), it's a five year old feature request, and while there are a few attempts at implementations using regions, they all fall short of usable solutions.
